### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by babrah** [jiangmiao/node-curl#12] opened 2012-12-07 05:42 UTC
Hello,  I'm trying the example with google.com and getting the error:
i am using MAC 10.8.2, "node": "0.8.14"

```
[ERROR] Error
Error: Cannot find module '/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl-custom/lib/../build/default/node-curl'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl-custom/lib/curl.js:8:12)
    at Object.<anonymous> (/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl-custom/lib/curl.js:79:4)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Object..js (/usr/local/lib/node_modules/node-dev/wrapper.js:121:15)
    at Module.load (module.js:356:32)
```

installation was successful:

```
npm http GET https://registry.npmjs.org/node-curl
npm http 304 https://registry.npmjs.org/node-curl

> node-curl@0.1.6 install /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl
> sh src/generate_curl_options_list.sh && node-waf configure build || true

generate src/integer_options.h
generate src/string_options.h
generate src/integer_infos.h
generate src/string_infos.h
generate src/double_infos.h
Setting srcdir to                        : /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl 
Setting blddir to                        : /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.040s)
Waf: Entering directory `/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build'
[1/2] cxx: src/node-curl.cc -> build/Release/src/node-curl_1.o
[2/2] cxx_link: build/Release/src/node-curl_1.o -> build/Release/node-curl.node
Waf: Leaving directory `/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build'
'build' finished successfully (0.673s)
node-curl@0.1.6 node_modules/node-curl
```

files in installed module:

```
babrah$ find node_modules/node-curl/build/
node_modules/node-curl/build/
node_modules/node-curl/build//.wafpickle-7
node_modules/node-curl/build//c4che
node_modules/node-curl/build//c4che/build.config.py
node_modules/node-curl/build//c4che/Release.cache.py
node_modules/node-curl/build//config.log
node_modules/node-curl/build//Release
node_modules/node-curl/build//Release/node-curl.node
node_modules/node-curl/build//Release/src
node_modules/node-curl/build//Release/src/node-curl_1.o
```

example curl.js:

```
babrah$ node node_modules/node-curl/examples/curl.js google.com

module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/lib/../build/default/node-curl'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/lib/curl.js:8:12)
    at Object.<anonymous> (/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/lib/curl.js:80:4)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by jiangmiao** [comment] 2012-12-07 05:57
The build looks succeeded. Do you have permission to access `/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/lib/../build/Release/node-curl.node` ?

or you could modify node-curl/lib/curl.js to

```
try {
  Curl = require(__dirname + '/../build/Release/node-curl').Curl;
} catch (e) {
  console.info(e);
  Curl = require(__dirname + '/../build/default/node-curl').Curl;
}
```

to see why require Release/node-curl failed.

**Comment by babrah** [comment] 2012-12-07 08:21
thanks for reply jiangmiao, yes i have access to node-curl.node file, and i tried what you asked for above code and i got this result::

```
babrah$ node node_modules/node-curl/examples/curl.js
[Error: dlopen(/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build/Release/node-curl.node, 1): no suitable image found.  Did find:
    /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build/Release/node-curl.node: mach-o, but wrong architecture]

module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/examples/../build/default/node-curl'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/examples/curl.js:30:10)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
```

and i tried to access this one too and got this result:

```
babrah$ node node_modules/node-curl/build/Release/node-curl.node

module.js:485
  process.dlopen(filename, module.exports);
          ^
Error: dlopen(/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build/Release/node-curl.node, 1): no suitable image found.  Did find:
    /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build/Release/node-curl.node: mach-o, but wrong architecture
    at Object.Module._extensions..node (module.js:485:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

**Comment by jiangmiao** [comment] 2012-12-07 09:08
Maybe the cause is the compiled node-curl.node's architecture is different from node.

What does `file /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build/Release/node-curl.node`  and `file $(which node)` output?  

Is the system 32bit or 64bit?

**Comment by babrah** [comment] 2012-12-07 09:12
i already mentioned its result above : ile /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build/Release/node-curl.node

and yes, its 64 BIT intel based MAC

didn't get  file $(which node) output?

**Comment by jiangmiao** [comment] 2012-12-07 09:18
if the shell doesn't support `$(which node)` then try `file [your node path]`
my output is

```
$ file node_modules/node-curl/build/Release/node-curl.node 
node_modules/node-curl/build/Release/node-curl.node: ELF 32-bit LSB shared object, Intel 80386, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=0x558438e7776c81d87ccd103521e0faa9fa666087, not stripped

$ file $(which node)
/usr/bin/node: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=0x00953bc1ba84e837baf3d26a3f7e6f45e3716416, stripped
```

both node and the node-curl are compiled in 32bit.

**Comment by babrah** [comment] 2012-12-07 09:24
it's giving this result:

```
babrah$ file node_modules/node-curl/build/Release/node-curl.node
node_modules/node-curl/build/Release/node-curl.node: Mach-O bundle i386
```

and this one:

```
babrah$ file $(which node)
/usr/local/bin/node: Mach-O universal binary with 2 architectures
/usr/local/bin/node (for architecture i386):    Mach-O executable i386
/usr/local/bin/node (for architecture x86_64):  Mach-O 64-bit executable x86_64
```

**Comment by jiangmiao** [comment] 2012-12-07 09:42
Try 
`ARCHFLAGS='-arch x86_64 -arch i386' npm install node-curl`
if failed then try
`ARCHFLAGS='-arch x86_64 -arch i386' CXXFLAGS=$ARCHFLAGS  npm install node-curl`

I didn't use Mac have no idea it works or not.

What's the c++ compiler in Mac?

**Comment by babrah** [comment] 2012-12-07 09:54
```
babrah$ gcc -v
Using built-in specs.
Target: i686-apple-darwin11
Configured with: /private/var/tmp/llvmgcc42/llvmgcc42-2336.11~67/src/configure --disable-checking --enable-werror --prefix=/Applications/Xcode.app/Contents/Developer/usr/llvm-gcc-4.2 --mandir=/share/man --enable-languages=c,objc,c++,obj-c++ --program-prefix=llvm- --program-transform-name=/^[cg][^.-]*$/s/$/-4.2/ --with-slibdir=/usr/lib --build=i686-apple-darwin11 --enable-llvm=/private/var/tmp/llvmgcc42/llvmgcc42-2336.11~67/dst-llvmCore/Developer/usr/local --program-prefix=i686-apple-darwin11- --host=x86_64-apple-darwin11 --target=i686-apple-darwin11 --with-gxx-include-dir=/usr/include/c++/4.2.1
Thread model: posix
gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)
```

**Comment by babrah** [comment] 2012-12-07 09:56
nothing worked, not even ARCHFLAGS

**Comment by jiangmiao** [comment] 2012-12-07 10:01
`ARCHFLAGS='-arch x86_64 -arch i386' CXXFLAGS=$ARCHFLAGS npm install node-curl`
What's the `file [node-curl.node]`  output generated by above command?

**Comment by babrah** [comment] 2012-12-07 10:03
```
babrah$ ARCHFLAGS='-arch x86_64 -arch i386' CXXFLAGS=$ARCHFLAGS npm install node-curl
npm WARN package.json PoetCanvas@0.0.1 No README.md file found!
npm http GET https://registry.npmjs.org/node-curl
npm http 304 https://registry.npmjs.org/node-curl

> node-curl@0.1.6 install /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl
> sh src/generate_curl_options_list.sh && node-waf configure build || true

generate src/integer_options.h
generate src/string_options.h
generate src/integer_infos.h
generate src/string_infos.h
generate src/double_infos.h
Setting srcdir to                        : /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl 
Setting blddir to                        : /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.042s)
Waf: Entering directory `/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build'
[1/2] cxx: src/node-curl.cc -> build/Release/src/node-curl_1.o
[2/2] cxx_link: build/Release/src/node-curl_1.o -> build/Release/node-curl.node
Waf: Leaving directory `/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build'
'build' finished successfully (0.674s)
node-curl@0.1.6 node_modules/node-curl
```

and then

```
babrah$ file node_modules/node-curl/build/Release/node-curl.node
node_modules/node-curl/build/Release/node-curl.node: Mach-O bundle i386
```

**Comment by jiangmiao** [comment] 2012-12-07 10:04
Try `CXXFLAGS="-m32 -m64 -arch i386 -arch x86_64"  npm install node-curl`

**Comment by babrah** [comment] 2012-12-07 10:06
```
babrah$ CXXFLAGS="-m32 -m64 -arch i386 -arch x86_64" npm install node-curl
npm WARN package.json PoetCanvas@0.0.1 No README.md file found!
npm http GET https://registry.npmjs.org/node-curl
npm http 304 https://registry.npmjs.org/node-curl

> node-curl@0.1.6 install /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl
> sh src/generate_curl_options_list.sh && node-waf configure build || true

generate src/integer_options.h
generate src/string_options.h
generate src/integer_infos.h
generate src/string_infos.h
generate src/double_infos.h
Setting srcdir to                        : /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl 
Setting blddir to                        : /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.040s)
Waf: Entering directory `/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build'
[1/2] cxx: src/node-curl.cc -> build/Release/src/node-curl_1.o
lipo: /var/folders/q_/spmsx4097p5gw1q9r1b5h3540000gn/T//ccvluEr6.out and /var/folders/q_/spmsx4097p5gw1q9r1b5h3540000gn/T//ccMWJXC2.out have the same architectures (x86_64) and can't be in the same fat output file
Waf: Leaving directory `/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build'
Build failed:  -> task failed (err #1): 
    {task: cxx node-curl.cc -> node-curl_1.o}
node-curl@0.1.6 node_modules/node-curl
```

**Comment by jiangmiao** [comment] 2012-12-07 10:07
Try `CXXFLAGS="-m64 -arch x86_64" npm install node-curl`

**Comment by babrah** [comment] 2012-12-07 10:08
same error:

```
babrah$ CXXFLAGS="-m64 -arch x86_64" npm install node-curl
npm WARN package.json PoetCanvas@0.0.1 No README.md file found!
npm http GET https://registry.npmjs.org/node-curl
npm http 304 https://registry.npmjs.org/node-curl

> node-curl@0.1.6 install /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl
> sh src/generate_curl_options_list.sh && node-waf configure build || true

generate src/integer_options.h
generate src/string_options.h
generate src/integer_infos.h
generate src/string_infos.h
generate src/double_infos.h
Setting srcdir to                        : /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl 
Setting blddir to                        : /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.041s)
Waf: Entering directory `/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build'
[1/2] cxx: src/node-curl.cc -> build/Release/src/node-curl_1.o
lipo: /var/folders/q_/spmsx4097p5gw1q9r1b5h3540000gn/T//ccluwqba.out and /var/folders/q_/spmsx4097p5gw1q9r1b5h3540000gn/T//ccUFWbEd.out have the same architectures (x86_64) and can't be in the same fat output file
Waf: Leaving directory `/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build'
Build failed:  -> task failed (err #1): 
    {task: cxx node-curl.cc -> node-curl_1.o}
node-curl@0.1.6 node_modules/node-curl
```

**Comment by jiangmiao** [comment] 2012-12-07 10:10
OK, Try the generic gcc way '-arch' is apple's gcc flag. `CXXFLAGS="-m64" npm install node-curl` if still failed. then I cannot solve the issue.

**Comment by babrah** [comment] 2012-12-07 10:13
```
babrah$ CXXFLAGS="-m64" npm install node-curl
npm WARN package.json PoetCanvas@0.0.1 No README.md file found!
npm http GET https://registry.npmjs.org/node-curl
npm http 304 https://registry.npmjs.org/node-curl

> node-curl@0.1.6 install /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl
> sh src/generate_curl_options_list.sh && node-waf configure build || true

generate src/integer_options.h
generate src/string_options.h
generate src/integer_infos.h
generate src/string_infos.h
generate src/double_infos.h
Setting srcdir to                        : /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl 
Setting blddir to                        : /Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.040s)
Waf: Entering directory `/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build'
[1/2] cxx: src/node-curl.cc -> build/Release/src/node-curl_1.o
[2/2] cxx_link: build/Release/src/node-curl_1.o -> build/Release/node-curl.node
ld: warning: ignoring file Release/src/node-curl_1.o, file was built for unsupported file format ( 0xcf 0xfa 0xed 0xfe 0x 7 0x 0 0x 0 0x 1 0x 3 0x 0 0x 0 0x 0 0x 1 0x 0 0x 0 0x 0 ) which is not the architecture being linked (i386): Release/src/node-curl_1.o
Waf: Leaving directory `/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/build'
'build' finished successfully (0.710s)
node-curl@0.1.6 node_modules/node-curl
```

and then

```
babrah$ node node_modules/node-curl/examples/curl.js google.com

module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/lib/../build/default/node-curl'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/lib/curl.js:8:12)
    at Object.<anonymous> (/Users/babrah/Desktop/nodeJadeDb/node_modules/node-curl/lib/curl.js:80:4)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

ok thanks bro for all your help, hope this will be sort out someday

**Comment by jiangmiao** [comment] 2012-12-07 10:17
The key is the generated node-curl.node is i386 and it should be x86_64。
as documentation
`-arch x86_64` will make it compile to x86_64 but the result is not, maybe some other flags I missed.

**Comment by romansky** [comment] 2013-01-05 11:36
having the issues here.. =/
Using Ubuntu 12.10
Linux laptopsky 3.5.0-21-generic #32-Ubuntu SMP Tue Dec 11 18:51:59 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
node v0.9.5

None of the tips helped :(

**Comment by jiangmiao** [comment] 2013-01-05 13:28
node v0.9 wasn't supported yet. because node is build with bind.gyp instead of node-waf. 
now I update node-curl to v0.1.7, it should support node v0.9.

**Comment by romansky** [comment] 2013-01-05 13:48
Reinstalled (without errors) Still getting this error:

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/romansky/Code/Workers/node_modules/node-curl/lib/../build/default/node-curl'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/romansky/Code/Workers/node_modules/node-curl/lib/curl.js:8:12)
    at Object.<anonymous> (/home/romansky/Code/Workers/node_modules/node-curl/lib/curl.js:80:4)
    at Module._compile (module.js:454:26)
    at Object.Module._extensions..js (module.js:472:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

#> file node_modules/node-curl/build/Release/node-curl.node
node_modules/node-curl/build/Release/node-curl.node: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=0xd0a11bca82e9255300f6ca48cb0824116ebe7211, not stripped

**Comment by jiangmiao** [comment] 2013-01-05 13:56
What's the output for command `node node_modules/node-curl/build/Release/node-curl.node` ?

**Comment by romansky** [comment] 2013-01-05 13:58
This is what I get: 

module.js:490
  process.dlopen(filename, module.exports);
          ^
Error: Symbol node_curl_module not found.
    at Object.Module._extensions..node (module.js:490:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:497:10)
    at process._tickCallback (node.js:386:13)

**Comment by jiangmiao** [comment] 2013-01-05 14:55
Just installed node v0.9 and fixed the issue.

**Comment by romansky** [comment] 2013-01-05 15:19
Not sure what you mean, I cloned the latest version from git, and still getting:

module.js:340
    throw err;
          ^
Error: Cannot find module '/tmp/node-curl/lib/../build/default/node-curl'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/tmp/node-curl/lib/curl.js:8:12)
    at Object.<anonymous> (/tmp/node-curl/lib/curl.js:80:4)
    at Module._compile (module.js:454:26)
    at Object.Module._extensions..js (module.js:472:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Any thoughts?

**Comment by jiangmiao** [comment] 2013-01-05 15:24
I mean I installed nodejs v0.9 and passed test
`npm install node-curl`

**Comment by romansky** [comment] 2013-01-05 15:27
Hmm.. I am running node v0.9.5 (are you running v0.9?), so I am still having the issue of "could not find module"

Any thoughts?

**Comment by jiangmiao** [comment] 2013-01-05 15:28
v0.9.6-pre

**Comment by jiangmiao** [comment] 2013-01-05 15:29
test if node-curl is built correct use command `node node_modules/node-curl/build/Release/node-curl.node`

**Comment by romansky** [comment] 2013-01-05 15:40
Thats what I did before..

#> node node_modules/node-curl/build/Release/node-curl.node

module.js:490
  process.dlopen(filename, module.exports);
          ^
Error: Symbol node_curl_module not found.
    at Object.Module._extensions..node (module.js:490:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:497:10)
    at process._tickCallback (node.js:386:13)
romansky@laptopsky:/tmp/curl$

**Comment by jiangmiao** [comment] 2013-01-05 15:43
I mean 
you said  `Error: Symbol node_curl_module not found.`
then I download nodejs v0.9 solve the issue 'Error: Symbol node_curl_module not found.'
you seems still didn't reinstalled node-curl.

**Comment by romansky** [comment] 2013-01-05 16:09
Here's a full transcript of me installing it and running it:
romansky@laptopsky:/tmp$ ll
total 0
romansky@laptopsky:/tmp$ vi /home/romansky/.bashrc 
romansky@laptopsky:/tmp$ cd /tmp/
CRX_75DAF8CB7768/                 jna/                              plugtmp-2/                        tmux-1000/
curl/                             libgksu-bQ2lBc/                   proj4js-1.1.0/                    VMwareDnD/
.dropbox-dist-new-0K2UrO/         node-curl/                        pulse-2L9K88eMlGn7/               vmware-root/
.dropbox-dist-new-HNN1zF/         orbit-romansky/                   pulse-4qO7qB9RiJbk/               .X11-unix/
hsperfdata_romansky/              pear/                             pulse-PKdhtXMmr18n/  
.ICE-unix/                        plugtmp/                          sbt_505044c6/  
jetty-0.0.0.0-8080-webapp-_-any-/ plugtmp-1/                        ssh-Sx8kBpao6eZw/  
romansky@laptopsky:/tmp$ cd /tmp/curl/
romansky@laptopsky:/tmp/curl$ ll
total 0
romansky@laptopsky:/tmp/curl$ npm install node-curl
npm http GET http://registry.npmjs.org/node-curl
npm http 304 http://registry.npmjs.org/node-curl

> node-curl@0.1.7 install /tmp/curl/node_modules/node-curl
> sh src/generate_curl_options_list.sh && (node-waf configure build || node-gyp rebuild)

extract constants from /usr/include/curl/curl.h
generate src/integer_options.h
generate src/string_options.h
generate src/integer_infos.h
generate src/string_infos.h
generate src/double_infos.h
Setting srcdir to                        : /tmp/curl/node_modules/node-curl 
Setting blddir to                        : /tmp/curl/node_modules/node-curl/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : not found 
'configure' finished successfully (0.023s)
Waf: Entering directory `/tmp/curl/node_modules/node-curl/build'
[1/2] cxx: src/node-curl.cc -> build/Release/src/node-curl_1.o
[2/2] cxx_link: build/Release/src/node-curl_1.o -> build/Release/node-curl.node
Waf: Leaving directory`/tmp/curl/node_modules/node-curl/build'
'build' finished successfully (0.656s)
node-curl@0.1.7 node_modules/node-curl
romansky@laptopsky:/tmp/curl$ node node_modules/node-curl/build/Release/node-curl.node

module.js:490
  process.dlopen(filename, module.exports);
          ^
Error: Symbol node_curl_module not found.
    at Object.Module._extensions..node (module.js:490:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:497:10)
    at process._tickCallback (node.js:386:13)
romansky@laptopsky:/tmp/curl$

**Comment by jiangmiao** [comment] 2013-01-05 18:35
I've installed node v0.9.5, so the environment should be same Try these steps:

```
$ git clone https://github.com/jiangmiao/node-curl.git
```

Cloning into 'node-curl'...
remote: Counting objects: 216, done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 216 (delta 118), reused 172 (delta 74)
Receiving objects: 100% (216/216), 38.53 KiB, done.
Resolving deltas: 100% (118/118), done.

```
$ cd node-curl
$ sh src/generate_curl_options_list.sh
```

extract constants from /usr/include/curl/curl.h
generate src/integer_options.h
generate src/string_options.h
generate src/integer_infos.h
generate src/string_infos.h
generate src/double_infos.h

```
$ node-gyp rebuild
```

gyp info it worked if it ends with ok
gyp info using node-gyp@0.8.2
gyp info using node@0.9.5 | linux | ia32
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/node-curl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/miao/.node-gyp/0.9.5/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/miao/.node-gyp/0.9.5',
gyp info spawn args   '-Dmodule_root_dir=/tmp/node-curl',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/tmp/node-curl/build'
  CXX(target) Release/obj.target/node-curl/src/node-curl.o
  SOLINK_MODULE(target) Release/obj.target/node-curl.node
  SOLINK_MODULE(target) Release/obj.target/node-curl.node: Finished
  COPY Release/node-curl.node
make: Leaving directory`/tmp/node-curl/build'
gyp info ok 

```
$ node build/Release/node-curl.node 
$ nm build/Release/node-curl.node |grep node_curl
```

000096d8 D node_curl_module

See if there is any difference.

## install from npm test

```
$ npm install node-curl 

> node-curl@0.1.7 install /tmp/node_modules/node-curl
> sh src/generate_curl_options_list.sh && (node-waf configure build || node-gyp rebuild)

extract constants from /usr/include/curl/curl.h
generate src/integer_options.h
generate src/string_options.h
generate src/integer_infos.h
generate src/string_infos.h
generate src/double_infos.h
sh: node-waf: command not found
make: Entering directory `/tmp/node_modules/node-curl/build'
  CXX(target) Release/obj.target/node-curl/src/node-curl.o
  SOLINK_MODULE(target) Release/obj.target/node-curl.node
  SOLINK_MODULE(target) Release/obj.target/node-curl.node: Finished
  COPY Release/node-curl.node
make: Leaving directory `/tmp/node_modules/node-curl/build'
node-curl@0.1.7 node_modules/node-curl
[miao@myhost tmp]$ node /tmp/node_modules/node-curl/build/Release/
.deps/          linker.lock     node-curl.node  obj.target/     
[miao@myhost tmp]$ node /tmp/node_modules/node-curl/build/Release/node-curl.node 
[miao@myhost tmp]$ 
```

**Comment by romansky** [comment] 2013-01-05 19:25
hmmm.. this is odd! using the first method works for me (I was able to run the examples), using the second method, even after removing "node-waf" from my environment (which was installed via Ubuntu's apt-get some time ago along with node) still produces the same end result: "Error: Symbol node_curl_module not found."

romansky@laptopsky:/tmp/node-curl$ nm build/Release/node-curl.node |grep node_curl
0000000000004d16 t _GLOBAL__sub_I_node_curl.cc
0000000000209fc0 D node_curl_module

romansky@laptopsky:/tmp/from_npm$ nm node_modules/node-curl/build/Release/node-curl.node |grep node_curl
0000000000004c96 t _GLOBAL__sub_I_node_curl.cc

Is the version in npm older?

**Comment by jiangmiao** [comment] 2013-01-05 19:47
if node.js is installed at /usr/local/bin,  in the environment PATH  it should be before /usr/bin. 

npm and node-gyp must be point to node.js v0.9.5 compiled. eg /usr/local/bin/node-gyp and /usr/local/bin/npm .

**Comment by jiangmiao** [comment] 2013-01-05 19:48
I've modified the package.json which make npm use node-gyp first instead of node-waf. and bump version to v0.1.8

**Comment by romansky** [comment] 2013-01-05 20:01
Thanks, its working out of the box now (npm install), Cheers!

**Comment by jiangmiao** [comment] 2013-01-05 20:03
nice.

**Closed as completed** 2013-02-19 16:53 UTC
